### ISSUE TITLE
The first LED is "blind"

### ISSUE THREAD

**Issue by profra** [JanBednarik/micropython-ws2812#3]
... any chance to fix it?

**Comment by JanBednarik** [comment]
Thanks for report, I will fix it.

**Comment by domgiles** [comment]
Hi Any update on this... I'm still seeing a blind first Neopixel. Only issue is I want just to show one. :-)

**Comment by domgiles** [comment]
Should have checked the forum, it appears the assignment on line 25 needs to be

buf_bytes = (0x88, 0x8e, 0xe8, 0xee)

http://forum.micropython.org/viewtopic.php?f=5&t=394&p=4591&hilit=neopixels#p4591

**Comment by uschoenh** [comment]
I had the same issue with my 24 LED Nepoixel ring. It was fixed after I changed the SPI init from `phase=1` to `phase=0` in the file ws2812.py 
`self.spi = pyb.SPI(spi_bus, pyb.SPI.MASTER, baudrate=3200000, polarity=0, phase=0)`
Now, also the first LED lights up.
